FROM registry.access.redhat.com/ubi9/ubi-init:latest

LABEL org.opencontainers.image.title="Cloudflared (systemd)" \
      org.opencontainers.image.authors="Gerard Braad"

# install tailscale
RUN curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm -o /tmp/cloudflared.rpm \
    && dnf install -y \
        /tmp/cloudflared.rpm \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && rm -f /tmp/cloudflared.rpm

# No need for entrypoint as base sets this
#ENTRYPOINT ["/sbin/init"]